# Generated by Django 4.1.7 on 2023-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='recipe_photos/')),
            ],
        ),
    ]
